### ISSUE TITLE
new mpi wrappers have broken mumps

### ISSUE THREAD

**Issue by francesco-ballarin** [NGSolve/ngsolve#71]
Hi,
I believe that the changes introduced in 060bef459263ea984a825408e6760e9a7b8a3d9e have broken mumps.

1. With
https://github.com/NGSolve/ngsolve/blob/060bef459263ea984a825408e6760e9a7b8a3d9e/CMakeLists.txt#L234
commented out it is not possible to create a dummy fortran lib at
https://github.com/NGSolve/ngsolve/blob/060bef459263ea984a825408e6760e9a7b8a3d9e/linalg/CMakeLists.txt#L34

Should be easy enough to solve, e.g. adding back `enable_language(Fortran)` before creating the dummy library, as I did in 
https://github.com/fem-on-colab/fem-on-colab/blob/2642344/ngsolve/patches/03-dummy-fortran-target

2. `NG_MPI_COMM_NULL` and `NG_MPI_Comm_c2f` seem to be missing, which results in an error when trying to compile `linalg/mumpsinverse.cpp`. 

```
/tmp/ngsolve-src/linalg/mumpsinverse.cpp: In constructor 'ngla::MumpsInverse<TM, TV_ROW, TV_COL>::MumpsInverse(const ngla::SparseMatrix<TM, TV_ROW, TV_COL>&, std::shared_ptr<ngcore::BitArray>, std::shared_ptr<const ngcore::Array<int> >, bool)':
/tmp/ngsolve-src/linalg/mumpsinverse.cpp:36:12: error: 'NG_MPI_COMM_NULL' was not declared in this scope
   36 |     : comm(NG_MPI_COMM_NULL, false)
      |            ^~~~~~~~~~~~~~~~
/tmp/ngsolve-src/linalg/mumpsinverse.cpp:253:29: error: there are no arguments to 'NG_MPI_Comm_c2f' that depend on a template parameter, so a declaration of 'NG_MPI_Comm_c2f' must be available [-fpermissive]
  253 |     mumps_id.comm_fortran = NG_MPI_Comm_c2f (comm);
      |                             ^~~~~~~~~~~~~~~
/tmp/ngsolve-src/linalg/mumpsinverse.cpp:253:29: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/tmp/ngsolve-src/linalg/mumpsinverse.cpp:285:29: error: there are no arguments to 'NG_MPI_Comm_c2f' that depend on a template parameter, so a declaration of 'NG_MPI_Comm_c2f' must be available [-fpermissive]
  285 |     mumps_id.comm_fortran = NG_MPI_Comm_c2f (comm);
      |                             ^~~~~~~~~~~~~~~
/tmp/ngsolve-src/linalg/mumpsinverse.cpp: In constructor 'ngla::ParallelMumpsInverse<TM, TVEC>::ParallelMumpsInverse(const ngla::BaseSparseMatrix&, std::shared_ptr<ngcore::BitArray>, std::shared_ptr<const ngcore::Array<int> >, std::shared_ptr<ngla::ParallelDofs>, bool)':
/tmp/ngsolve-src/linalg/mumpsinverse.cpp:763:29: error: there are no arguments to 'NG_MPI_Comm_c2f' that depend on a template parameter, so a declaration of 'NG_MPI_Comm_c2f' must be available [-fpermissive]
  763 |     mumps_id.comm_fortran = NG_MPI_Comm_c2f (comm);
      |                             ^~~~~~~~~~~~~~~
/tmp/ngsolve-src/linalg/mumpsinverse.cpp:812:29: error: there are no arguments to 'NG_MPI_Comm_c2f' that depend on a template parameter, so a declaration of 'NG_MPI_Comm_c2f' must be available [-fpermissive]
  812 |     mumps_id.comm_fortran = NG_MPI_Comm_c2f (comm);
      |                             ^~~~~~~~~~~~~~~
/tmp/ngsolve-src/linalg/mumpsinverse.cpp: In instantiation of 'ngla::MumpsInverse<TM, TV_ROW, TV_COL>::MumpsInverse(const ngla::SparseMatrix<TM, TV_ROW, TV_COL>&, std::shared_ptr<ngcore::BitArray>, std::shared_ptr<const ngcore::Array<int> >, bool) [with TM = double; TV_ROW = double; TV_COL = double]':
/tmp/ngsolve-src/linalg/mumpsinverse.cpp:987:18:   required from here
/tmp/ngsolve-src/linalg/mumpsinverse.cpp:253:45: error: 'NG_MPI_Comm_c2f' was not declared in this scope
  253 |     mumps_id.comm_fortran = NG_MPI_Comm_c2f (comm);
```
(and continues like that for a few more occurences, see https://github.com/fem-on-colab/fem-on-colab/actions/runs/9147331334/job/25148606731 for the full log)

Thanks,
Francesco

cc @mhochsteger @JSchoeberl

**Comment by mhochsteger** [comment]
Hi Francesco,
Thanks for the report, I will have a look at your suggestions. As a workaround for now, there are two possibilities.
- Disable the MPI wrapper (-DUSE_MPI_WRAPPER=OFF).
- Build MUMPS yourself and use the python wrapper PyMUMPS (@ChrLackner is there any docu/example on this?)

Our plan is to move from compile-time options for (and automatic compilation of) solvers to run-time plugins like PyMUMPS, so the second option will be more future-proof.
Note that with the MPI-wrapper now enabled in pip-packages (only pre-release so far, and depending on mpi4py 4.0.0.dev0), there should be no need anymore for you to compile NGSolve yourself. So I advise to try using PyMUMPS and enable the MPI wrapper (or even use ngsolve-dev from pip).

**Comment by francesco-ballarin** [comment]
Thanks @mhochsteger. I'll keep using MPI wrappers then, and temporarily disable MUMPS until PyMUMPS is tested.

All my bug reports come from https://github.com/fem-on-colab/fem-on-colab : I won't ever use packages from pypi there.

**Comment by francesco-ballarin** [comment]
Closing since https://github.com/NGSolve/netgen/commit/1e7624c7f589cd08c7915a73a10da665a8cc4eec has disabled the new mpi wrappers by default. May need to re-open if the default will be set to `ON` in future.
